# General configuration for hyperspectral image processing and CNN-based analysis
config:
  data:
    input_path: "data/hyperspectral_images/"        # Path to hyperspectral images
    output_path: "results/"                         # Directory for output results
    big_tiff: true                                  # is Tiff image contains all band or need to parse different tiff files into one array
    zone: 'Israel'                                  # How to convert the geo tiff coorindates into real world cooridantes
    bands_to_use: [10, 20, 30, 40, 50]              # Selected spectral bands for processing
    spatial_resolution: 1.0                         # Resolution of the image in meters
    label_file: "data/labels.csv"                   # Path to labels for supervised learning
    rois: [[-83.14294, -83.00007,42.34429, 42.39170]] # ROI to crop the full hyperspectral image and its X,Y in format of [xmin_cut, xmax_cut, ymin_cut, ymax_cut]

  preprocessing:
    normalization: true                             # Whether to normalize pixel values
    normalization_type: "min-max"                   # Type of normalization (min-max, z-score)
    spectral_smoothing: false                       # Whether to apply spectral smoothing
    
    georeferencing:                                 # Georeferencing to apply
      merge_threshold: [0.05]                       # Threshold for merging
      merge_method: "mean_min"                      # Method for merging segments
      osx_map_mask_path:                            # Relative path for OpenStreetMap roads mask
        "data/Detroit/masks_OpenStreetMap/Detroit_OpenSteet_roads_mask.npz"
      dijkstra_map_mask_path:                       # Relative path for merged segments ID roads mask
        "data/Detroit/masks_OpenStreetMap/Detroit_dijkstra_roads_mask.npz"
  
  augmentations:                                  # Augmentations to apply
    rotation: true                                # Enable random rotations
    flipping: true                                # Enable random horizontal/vertical flips
    cropping: true                                # Enable random cropping

  cnn_model:
    architecture: "3D-CNN"                        # Type of CNN architecture (e.g., 3D-CNN, 2D-CNN)
    input_shape: (128, 128, 12)                   # Shape of input tensor (height, width, bands)
    num_classes: 4                                # Number of target classes for classification
    base_filters: 32                              # Number of filters in the first layer
    dropout_rate: 0.5                             # Dropout rate for regularization
    activation_function: "relu"                   # Activation function to use
    optimizer: "adam"                             # Optimizer for training
    loss_function: "categorical_crossentropy"     # Loss function for training
    crop_size: 128                                # Size of the cropped patches (crop_size, crop_size)
    overlap : 0.2

  training:
    batch_size: 16                                # Batch size for training
    epochs: 100                                    # Number of epochs to train the model
    learning_rate_ini: 0.001                      # Initial learning rate
    learning_rate_ref: 0.5e-4                     # Learning rate in the refinment phase
    learning_rate_focal: 1e-3                     # Learning rate after switching to focal loss
    learning_rate_schedule:                       # Learning rate schedule
      type: "exponential_decay"                   # Type of schedule (e.g., step_decay, exponential_decay)
      decay_rate: 0.95                            # Decay rate for the learning rate
      decay_steps: 10                             # Number of steps before applying decay
    validation_split: 0.2                         # Fraction of the dataset to use for validation

  output:
    save_model: true                              # Whether to save the trained model
    model_save_path: "models/trained_model.h5"    # Path to save the trained model
    log_path: "logs/training.log"                 # Path for training logs
    evaluation_metrics:                           # Metrics to evaluate during and after training
      - "accuracy"
      - "precision"
      - "recall"
      - "f1_score"

